import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav/Nav";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect fonts to help early font fetches (next/font still manages font files) */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Inline minimal critical CSS for the hero LCP paragraph to avoid waiting for full CSS */}
        <style dangerouslySetInnerHTML={{ __html: `
          .lcp-critical { font-size: 1.5rem; color: #e6eef8; max-width: 48rem; margin-bottom: 1.5rem; }
        ` }} />
      </head>
      <body className={`${inter.variable} antialiased site-gradient`}>
        <div className="min-h-screen flex flex-col">
          <Nav />
          <main className="flex-1 overflow-auto">{children}</main>

          <footer className="w-full border-t border-white/5 bg-transparent">
            <div className="max-w-7xl mx-auto px-6 lg:px-12 py-6 flex items-center justify-between text-sm text-gray-400">
              <div>© {new Date().getFullYear()} Adam — Built with Next.js</div>
              <div className="flex items-center gap-4">
                <a href="https://github.com/AdamSWS" target="_blank" rel="noopener noreferrer" className="hover:text-white">GitHub</a>
                <a href="https://www.linkedin.com/in/adam-s-491036232/" target="_blank" rel="noopener noreferrer" className="hover:text-white">LinkedIn</a>
                <a href="/downloads/adam_shaar_softres.pdf" download className="hover:text-white" aria-label="Download resume">Resume</a>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
