import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "../components/Nav/Nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased site-gradient`}>
        <div className="min-h-screen flex flex-col">
          <Nav />
          <main className="flex-1 overflow-auto">{children}</main>

          <footer className="w-full border-t border-white/5 bg-transparent">
            <div className="max-w-7xl mx-auto px-6 lg:px-12 py-6 flex items-center justify-between text-sm text-gray-400">
              <div>© {new Date().getFullYear()} Adam — Built with Next.js</div>
              <div className="flex items-center gap-4">
                <a href="https://github.com/AdamSWS" target="_blank" rel="noopener noreferrer" className="hover:text-white">GitHub</a>
                <a href="https://www.linkedin.com/in/adam-s-491036232/" target="_blank" rel="noopener noreferrer" className="hover:text-white">LinkedIn</a>
                <a href="/downloads/adam_shaar_softres.pdf" download className="hover:text-white" aria-label="Download resume">Resume</a>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
